export const LOGIN = "AUTH/LOGIN"
export const REGISTRATION = "AUTH/REGISTRATION"
export const LOGOUT = "AUTH/LOGOUT"
export const AUTHORISE = "AUTH/AUTHORISE"
export const CLEAR_CREDENTIAL = "AUTH/CLEAR_CREDENTIAL"

