export const SET_ALL_BOOKS = "BOOK/SET_ALL"
export const GET_ALL_BOOKS = "BOOK/GET_ALL_BOOKS"
export const ADD_AUTHOR_BOOK = "BOOK/ADD_AUTHOR_BOOK"
export const SET_AUTHOR_BOOKS = "BOOK/SET_AUTHOR_BOOKS"
export const GET_AUTHOR_BOOKS = "BOOK/GET_AUTHOR_BOOKS"
export const CREATE_AUTHOR_BOOK = "BOOK/CREATE_AUTHOR_BOOK"
export const UPDATE_AUTHOR_BOOK = "BOOK/UPDATE_AUTHOR_BOOK"
export const DELETE_AUTHOR_BOOK = "BOOK/DELETE_AUTHOR_BOOK"
export const CLEAR_AUTHOR_BOOKS = "BOOK/CLEAR_AUTHOR_BOOKS"
export const CLEAR_ALL_BOOKS = "BOOK/CLEAR_ALL_BOOKS"
export const CLEAR_BOOK_STATE = "BOOL/CLEAR_STATE"
export const ADD_BOOK = "BOOK/ADD_BOOK"


