export const genres:string[] = [
    "action",
    "hurt",
    "comfort",
    "pov",
    "pwp",
    "songfic",
    "angst",
    "dystopia",
    "darkfic",
    "detective",
    "drama",
    "friendship",
    "curtain",
    "malicious",
    "historical",
    "love",
    "mysticism",
    "mythical",
    "omegaverse",
    "parody",
    "firstime",
    "fantasy",
    "fluff",
    "fiction",
    "horrors",
    "soulmates",
    "romance",
    "psychology",
    "humdrum",
]


export type GenresType = typeof genres
