export const IS_ADMIN_URL = "/admin/i"
export const BLOCK_USER_URL = "/admin/block"
export const UNBLOCK_USER_URL = "/admin/unblock"
export const GET_PROFILE_URL = "/admin/profile"
export const SET_ADMIN_ROLE_URL = "/admin/setAdmin"
export const REMOVE_ADMIN_ROLE_URL = "/admin/removeAdmin"