export const REGISTRATION_URL = "/credential/registration"
export const LOGIN_URL = "/credential/login"
export const LOGOUT_URL = "/logout"
export const CHECK_AUTH_URL = "/credential/check"
export const CONFIRM_EMAIL_URL = "/confirm"