export const GET_BOOK_URL = "/book"
export const LIST_BOOKS_URL = "/book/all"
export const BOOKS_BY_USER_ID_URL = "/book/user"
export const BOOK_CREATE_URL = "/book/create"
export const BOOK_UPDATE_URL = "/book/update"
export const DELETE_AUTHOR_BOOK_URL = "/book/delete"
export const UPDATE_AUTHOR_BOOK_URL = "/book/update"
