export * from "./auth"
export * from "./book"
export * from "./cloudinary"
export * from "./user"
export * from "./chapter"
export * from "./admin"
export * from "./comment"

export const BASE_URL = "http://localhost:5000"
export const MAIN_PAGE_URL = "/"
