export const CREATE_USER_URL = "/user/create"
export const GET_ALL_USER_URL = "/user/getAll"
export const DELETE_USER_URL = "/user/delete"
export const GET_CURRENT_USER_PROFILE_URL = "/user/get"
export const UPDATE_CURRENT_USER_INFORMATION = "/user/update"
export const UPDATE_CURRENT_USER_IMAGE = "/user/updateImage"